### ISSUE TITLE
Will this result in memory leaks?

### ISSUE THREAD

**Issue by aidan-gallagher** [mkirchner/linked-list-good-taste#10]
Will both examples (CS101 and elegant) result in memory leaks because the target not is not freed after being removed from the list?

**Comment by bnert** [comment]
That looks to be the case! Given this is a demonstration of taste, it is unnecessary to free memory. OS should cleanup any memory leaks on program exit.

Hope this helps answer your question!

**Comment by mkirchner** [comment]
@aidan-gallagher, @bnert, thank you for starting the discussion.

The code in this example makes no assumptions about memory management.

The `remove_elegant(...)` and `remove_cs101(..)` functions both take a `target` pointer to a `list_item` as a parameter and remove the `target` item from the list. Since the calling function still has a `list_item` pointer to `target` (the parameter it supplied to the removal function), it can free allocated memory if appropriate.

Closing this for now.
