### ISSUE TITLE
do you think it would be doable in other languages like python for a linked list?

### ISSUE THREAD

**Issue by xihajun** [mkirchner/linked-list-good-taste#13]

**Comment by mkirchner** [comment]
Hi @xihajun, closing this since it’s a question that’s specific to Python and at the same time goes beyond the scope of this project. 

That said, here’s my take.

Python does not have a pointer construct and as such, double pointer “implementations” in Python likely are educational at best.

If you are interested in the actual list type implementation in cpython (which is in C and makes use of pointers), I recommended you check [the source](https://github.com/python/cpython/blob/main/Include/cpython/listobject.h).

**Comment by xihajun** [comment]
Thanks @mkirchner
