### ISSUE TITLE
pointer vs value equality

### ISSUE THREAD

**Issue by vlucent** [mkirchner/linked-list-good-taste#21]
I was confused for the longest time why pointers were being tested for equality, rather than the value. was there a specific reason for this? 

seems a bit silly to need to know memory location of target to remove it, and it renders the value element to be unnecessary in this example, along with the whole thing about the integers being randomized.

**Comment by mkirchner** [comment]
@vlucent This is simply to avoid having to define value equality in the example. You could write your own `find_xyz()` functions (see `find_indirect()` in `list.c` for an example) or pass function pointers to implementations of equality predicates in a practical implementation if that covers your use case better (I avoided going down that route since it was secondary to introducing the concept of an indirect pointer).
