### ISSUE TITLE
test doesn't compile on GCC

### ISSUE THREAD

**Issue by dcorderoch** [mkirchner/linked-list-good-taste#6]
```
gcc (Ubuntu 10.2.0-13ubuntu1) 10.2.0
```
reports

```
$make test
gcc -Wall -O2 -o test_list test_list.c
test_list.c:7:20: error: variably modified ‘items’ at file scope
    7 | static IntListItem items[n];
      |                    ^~~~~
make: *** [Makefile:7: test] Error 1
```

in line 6 `n` is defined as a `const size_t`, C requires compile-time constant expressions, `const` in C doesn't mean that

by changing

```
const size_t n = 1000;
```
to
```
#define n 1000
```

the problem gets fixed

**Comment by mkirchner** [comment]
@dcorderoch thanks for spotting this. It seems that your GCC is using the C89 standard to compile the code. The code should not trigger an error for C99 and above.

That said, you are still right - `const size_t` does not declare a compile-time constant in C and the array declaration works in C99 and above since it's treated as a variable length array. And that wasn't the intention.

Added your fix in 3f4eb2d.
