### ISSUE TITLE
Related to derivatives of data structures

### ISSUE THREAD

**Issue by FranklinChen** [mkirchner/linked-list-good-taste#8]
I couldn't help noticing that the technique used here is related to the same used (in a functional setting) of the concept of a derivative of a data structure, aka "zipper" https://en.wikipedia.org/wiki/Zipper_(data_structure) . The idea is to use a "hole", an indirection, to hang onto the context of a place where things may be modified. It can be applied (and in a mechanically standardized way, "differentiation") to all kinds of tree structures beyond lists. Very elegant indeed. You may want to point to the literature on derivatives of data structures.

**Comment by mkirchner** [comment]
Hi @FranklinChen, thanks for the comment!

I looked at [Huey's paper][huey] and I am doubtful that there is an actual relationship to the zipper (or derivatives) here. AFAICT the idea behind the zipper is to walk an edit focus along a tree (or tree-like structure like a list for e.g. gap buffers) and close behind the zipper as you move along. The obvious analogy with the indirect pointer idea is that you take a different viewpoint as you move through the data structure, but it is my understanding that you need to explicitly implement "zippability" in the data structure if you want it (since it requires back-pointers to tree nodes, etc). This is not at all the case in the linked list example: the data structure is a vanilla linked list; the only change is to use an indirect pointer instead of a direct one.

So, in the best case (and with limited understanding of Huey's paper), that might be the least-effort implementation example of a zipper, but I'd rather not ask the reader to diverge into a realm of potential complexity that is not necessary to understand the idea behind Linus' "good taste" argument (which is why I wrote the article in the first place).

Hope this works for you and thanks again for the interesting sidetrack.

[huey]: https://www.st.cs.uni-saarland.de/edu/seminare/2005/advanced-fp/docs/huet-zipper.pdf
